{% set name = "go-archiver" %}
{% set version = "3.5.0" %}
{% set sha256 = "8f2e3ad68553f6b58bf99e8635ff0953f62ff0a7804da7658954ffaa7d0aaa0a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mholt/archiver/archive/v{{ version }}.tar.gz
  folder: src/github.com/mholt/archiver
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  detect_binary_files_with_prefix: false

requirements:
  build:
    - go
    - git

test:
  commands:
    - test -f $PREFIX/bin/arc  # [unix]
    - arc -h || true  # [unix]
    - if not exist "%LIBRARY_BIN%\\arc.exe" exit 1  # [win]
    - arc -h || exit 0  # [win]

about:
  home: https://github.com/mholt/archiver
  license: MIT
  license_family: MIT
  license_file: src/github.com/mholt/archiver/LICENSE
  summary: Make and extract common archive formats such as .zip, and .tar.gz
  description: |
    Easily create and extract .zip, .tar, .tar.gz, .tar.bz2, .tar.xz,
    .tar.lz4, .tar.sz, and .rar (extract-only) files with Go. Package
    archiver makes it trivially easy to make and extract common archive
    formats. Simply name the input and output file(s). Files are put into the
    root of the archive; directories are recursively added, preserving
    structure.
  doc_url: https://godoc.org/github.com/mholt/archiver
  dev_url: https://github.com/mholt/archiver

extra:
  recipe-maintainers:
    - nehaljwani
