travis:
  secure:
    BINSTAR_TOKEN: S/5O1uTpbA1UmWW0X97odjb4vyLPEiZhAtYTa8ZNf33vJM2ZNepKOea4LtWCs+r+/qgUY134k/DZnEPs5HJ1qKbhewwMewc5KoBv6+77zAvarBe642AOgwOyjh7Wa02eTGYWtKuBbQazZOnEJFgckcS6eQoOzM8tJ7FZcpVvtagp2mKU98A0zUj+OBHjo/F1ij4NzrrWADE7p1JdIEIECuvIkCXL6lr8/uJS4KuCRNwOiYRNF5bjd1jD3Z67ezf3U5+Q0aWvGS/RMftGKUNJ6opVQqaCXyaLHqLnwAW0INr+IfNPSZAAngwPQ4OeoWIQ2ye6Sm/vJxeGCQ8Qzb1xeRUjqMgyhKszQ4oCm1BsrRS5n2sMcm6ufq0OnFL8U1ZYOi9eH4vJ7uw90AD6v4Gov59Utg7YNB7ain2HiYWGvOsE348pAPPcgWJgLSv6sTMMRSHoiKCLd9yDEAQLc6fZ8UYNTXny8qpHLqWfrkOjfH+aO9rIc3RBAPGMdQBYdTSDPAnBH5f+ATc+Odf26LvRQOgjpBaUCmIPuSGjcTEjL9ZVEGbyR+8sfy3rhlSPpzprz2oILE2DudLs2gwbBh3XUwT2bWjfiB9T2gouZo8cii1yGFZOifyr2H61YfRxwFspGlUm1fb5Mlaay/g+w7zX8KxDYNhNxMWaIqqbMgq7yLc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
