travis:
  secure:
    BINSTAR_TOKEN: KsbL7C3mRfn/fMeZdUV6/VlW7NAyXfrWAIlLyGvg4ezBTUN+N28QDIEQYZ0S0SsPddvMXTc4TxYDET37eE6usW46yS6n4BWs1NFB803bYndP5Z5EzR1Yk3p0mLxUoX+zYWA/WHtF78SM7E5tcpEUk7EP1JO/g8Qfpoei10LuAWZrcS45fp00A0IcFqr7qyIP+Fg49bOAa2ZGZVKxAvgAjkQyrV71ie8X6+/e9mrdKx3B0DQXU8g8gmE4RrYq9FweLQNdacF5e/BKKT0fGhkf6SuP8rTqymL9hQvZ+loZHbrw3+K73MkXm0C/T0NcA70Sd5pNvopg7kT5eCqKqLJ7qVwSMqjteudOYHBi+2sMTYlJ4Ez4q6vvajYFbyjnmEgiQL5kokFCkPnA2KllhqNCYQ6NTxDbqTL32s+eCD4xEDgr8q2aLm79YC82+X01Eu+lV7UptoxGzqsgVl4QpuFgbsgHg+4GAzlHhovid9fqC74+eyqiVpEC/cU2yI0QgQh67dAjsYk++piO+MyzTgx3vVl/J5a1TmcKfXJ5xsf1Zo2dMXRCvngElZfswAyakNhcYO0YFco3SZF9B4Og6wmZ7ytSFwJInkHZqAUCj0rbbyxfI2uEf0v955SzwBPmgtIhCgvAf/wgAKqOo3NJJDr6r5FBIbruagHY14roiiJv1e0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
