travis:
  secure:
    BINSTAR_TOKEN: NoHsUuZVXHxA2drn/O1TSUobrVSAEsPHBqNF75bUKpd7ESMyJO5nfz5dA5AzgwnsnymvbbDQmBswIs/PkNBMQp0eahNjWqNqA4rFVcHoXPrZZ8QzBXHoIGTFE5GKGSa7c2bgGQI9ktB1ev+rauHwgeWry38yDVJX+9jtHj8OFqisrtTOrJqDd1bc7c+8jKesc2Xsh0b24jJ0C5+OVcDBedk/sm9RiWp8gnJGRMcMI97gFP2MwjxxagSAHjPXxvtKQOyOycpCWaSPGS1WppqOk+us7gPsQUkK/qg0kWbiNhLVq1VetsDsmm3f3I80t+ck/pcvW49ClVZIlD5/2Dp6NFmhkx/hOKg+WWEh64HmxcFHXTHhvH+46ikPXfOogCvRhi+QTbAd6qeZRMo7YMWJrZsoeaBhfpVC55dqwpe5uGzYkQU51T0Hjgi5GngNXL4zzJeUtfbcPnBf13O3Mhn5+xHiFCr0r3XD1gkhO7J9Er/5jCj3V2KUhL5nAHchQIhBhMaXh4/RSxQIkHe8k7II2WJgLE5YDLJ96B0INYHVVc5vGA0Ms2PgutLpagKTPMFps2mqf43sbgX1cYLVjyNoCjzHf8JhXK20+YidkKmR6kiyYa7ePdVUgxdfLy9AMaPrS33t03kuANqIO/WWpYxVVL3FK+lo0z9AaFjnbmUg3ow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
